# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2022

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-windows.zip -OutFile $(Build.SourcesDirectory)/premake.zip
      Expand-Archive -Force $(Build.SourcesDirectory)/premake.zip $(Build.SourcesDirectory)/premake/
    failOnStderr: true
- task: CmdLine@2
  inputs:
    script: '$(Build.SourcesDirectory)/premake.exe vs2022'
    failOnStderr: true