# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
        tar -xvf premake-5.0.0-alpha16-linux.tar.gz
        sudo chmod a+x premake5
        sudo mv premake5 /usr/local/bin
        ./build.sh clean
        ./build.sh release
        cp linux/bin/release/librive.so $(Build.SourcesDirectory)/runtimes/linux-x64/native/librive.so
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/runtimes'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      verbose: true
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/'
      artifact: 'Build Libs'
      publishLocation: 'pipeline'